language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - cd src/tests/
  - coverage run --rcfile=../../.coveragerc --source=.,.. -m unittest discover
after_success:
  - coveralls